# Generated by Django 3.0.5 on 2021-02-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='genres',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='api.Categories'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='api.Genres'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название произведения'),
        ),
    ]
