# Generated by Django 3.0.5 on 2021-02-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210215_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
